### ISSUE TITLE
How to compile this with GHC 9.6.4?

### ISSUE THREAD

**Issue by lylek** [ucsd-progsys/lh-plugin-demo#22]
I see the stack configuration file for GHC 9.2.5, but I'd like to update that to use GHC 9.6.4 (or GHC 9.6.3). How does one go about figuring out what versions of files to specify in the stack.yaml? I thought I could do this by finding the version of liquidhaskell tagged v0.9.6.3, and noting the versions of everything, and replacing the versions in the stack.yaml with those:

```
resolver: nightly-2023-11-27
packages:
  - .
extra-deps:
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: fc4a89b91fad8b7a02b72901381d4358a470e230
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: eb339f9abdf073f8d9f0c446c309006fdf49ed42

nix:
  packages: [cacert, git, hostname, z3]
```

But stack couldn't construct a build plan. I tried `allow-newer: true`, but that led to other compilation failures.
